version: 0.2

phases:
  install:
    commands:
      - echo "Environment Variables:"
      - echo "S3_BUCKET=$S3_BUCKET"
      - echo "LAYER_KEY=$LAYER_KEY"
  build:
    commands:
      - echo "Listing all files..."
      - ls -R
      - echo "Uploading Pillow layer..."
      - aws s3 cp layers/pillow-layer.zip s3://$S3_BUCKET/$LAYER_KEY
artifacts:
  files:
    - '**/*'
